apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mcp-config-pvc
spec:
  volumeName: mcp-config 
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
