apiVersion: v1
kind: PersistentVolume
metadata:
  name: mcp-config 
spec:
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  nfs:
    path: /volume1/Kubernetes/deepweb-proxy/data     # The path to your config
    server: 192.168.42.8     # Your NFS server with Media
  mountOptions:
    - vers=4
    - minorversion=1
    - noac
---
 apiVersion: v1
 kind: PersistentVolume
 metadata:
   name: nfs-i2p-data-pv
 spec:
   capacity:
     storage: 1Gi
   accessModes:
     - ReadWriteOnce
   nfs:
     path: /volume1/Kubernetes/deepweb-proxy/i2pcache
     server: 192.168.42.8
   mountOptions:
      - vers=4
      - minorversion=1
      - noac
