apiVersion: v1
kind: Service
metadata:
  name: mcp-gemma-crawler-service
  labels:
    app: mcp-crawler
spec:
  selector:
    app: mcp-crawler
  ports:
    - name: webserver
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: tor-socks
      port: 9050
      targetPort: 9050
      protocol: TCP
    - name: i2p-proxy
      port: 4444
      targetPort: 4444
      protocol: TCP
  type: ClusterIP  # Default type, only accessible within the cluster